@extends('layouts.store')

@section('title', 'Checkout — sss')
@section('page-key', 'checkout')

@section('content')
<div class="container-wide section"><div class="page-heading"><div class="crumb"><a href="index.html">Home</a> / Checkout</div><h1>Checkout</h1><p></p></div><div class="checkout-progress">01 Bag <span>—</span> <strong>02 Checkout</strong> <span>—</span> 03 Confirmation</div><div id="checkout-empty"></div><div id="checkout-layout" class="checkout-layout"><form id="checkout-form"><div class="panel"><h2>Delivery details</h2><p class="muted">Already have an account? <a href="login.html">Sign in</a></p><div class="field"><label for="full-name">Full name</label><input class="form-control" id="full-name" name="full-name" type="text" value="" required autocomplete="name"></div><div class="field"><label for="email">Email address</label><input class="form-control" id="email" name="email" type="email" value="" required autocomplete="email"></div><div class="field"><label for="phone">Phone number</label><input class="form-control" id="phone" name="phone" type="tel" value="" required autocomplete="tel" pattern="[0-9+ ()-]{10,18}"></div><div class="field"><label for="address">Address</label><input class="form-control" id="address" name="address" type="text" value="" required autocomplete="street-address"></div><div class="two-col"><div class="field"><label for="city">City</label><input class="form-control" id="city" name="city" type="text" value="" required autocomplete="address-level2"></div><div class="field"><label for="state">State</label><input class="form-control" id="state" name="state" type="text" value="" required autocomplete="address-level1"></div></div><div class="field"><label for="pin">PIN code</label><input class="form-control" id="pin" name="pin" type="text" value="" required autocomplete="postal-code" pattern="[0-9]{6}" maxlength="6"></div></div><div class="panel"><h2>Payment method</h2><label class="payment-option"><input type="radio" name="payment" value="cod" checked> Cash on delivery <span>Demo</span></label><p class="small muted">Frontend preview only. No payment is collected and no real order is placed.</p><label class="check"><input type="checkbox" required> I agree to the <a href="terms.html">terms & conditions</a>.</label><button class="btn btn-dark w-100" type="submit">Place demo order ↗</button></div></form><aside id="checkout-summary"></aside></div></div>
@endsection

