@extends('layouts.sss-admin')
@section('title', $order['id'])
@section('subtitle', 'The little details behind a good order.')
@section('actions')<a class="btn btn-light" href="{{ route('admin.orders.index') }}">← All orders</a><button class="btn btn-dark" data-print><x-sss-admin.icon name="download" /> Print order</button>@endsection
@section('content')
<div class="order-banner"><div><span class="status status-{{ strtolower($order['status']) }}">{{ $order['status'] }}</span><span class="status status-{{ strtolower($order['payment']) }}">{{ $order['payment'] }}</span></div><span>Placed {{ $order['date'] }} · {{ $order['items'] }} items</span></div>
<div class="form-layout"><div><section class="panel table-panel"><div class="panel-heading"><h2>Order items</h2><span class="muted small">Sample order</span></div><div class="table-responsive"><table class="admin-table"><thead><tr><th>Product</th><th>Price</th><th>Quantity</th><th>Total</th></tr></thead><tbody>
@foreach($order['lines'] as $line)
@php($item = collect(config('sss-admin-demo.products'))->firstWhere('id', $line['product_id']))
<tr><td><div class="product-cell"><img src="{{ asset('sss-admin/images/product-'.$item['image'].'.svg') }}" alt="{{ $item['name'] }}"><div><strong>{{ $item['name'] }}</strong><small>{{ $item['sku'] }} · Size {{ $line['size'] }}</small></div></div></td><td>₹{{ number_format($item['price']) }}</td><td>{{ $line['qty'] }}</td><td>₹{{ number_format($item['price'] * $line['qty']) }}</td></tr>
@endforeach
</tbody></table></div><div class="order-totals"><div><span>Subtotal</span><strong>₹{{ number_format($order['subtotal']) }}</strong></div><div><span>Shipping</span><strong>{{ $order['shipping'] ? '₹'.number_format($order['shipping']) : 'Free' }}</strong></div><div class="grand-total"><span>Total</span><strong>₹{{ number_format($order['total']) }}</strong></div><p class="small muted">Sample prices include taxes.</p></div></section><section class="panel"><h2>Order activity</h2><div class="timeline"><div><i></i><strong>Order created</strong><small>{{ $order['date'] }} · Customer checkout</small></div><div><i></i><strong>Payment: {{ $order['payment'] }}</strong><small>Illustrative payment state</small></div><div><i></i><strong>Fulfilment: {{ $order['status'] }}</strong><small>Current sample status</small></div></div></section><section class="panel"><h2>Internal note</h2><form onsubmit="return false" data-preview-form="Note preview complete. No note was saved."><label class="visually-hidden" for="order-note">Internal order note</label><textarea class="form-control" id="order-note" rows="3" placeholder="Add a note for your team…" required></textarea><button class="btn btn-light mt-3">Preview note</button></form></section></div><aside><section class="panel"><h2>Customer</h2><div class="customer-identity"><span class="profile-avatar">{{ substr($order['customer'], 0, 1) }}</span><div><strong>{{ $order['customer'] }}</strong><small>{{ $order['email'] }}</small></div></div><hr><h3>Delivery address</h3><p class="muted">{{ $order['customer'] }}<br>24 Sample Avenue<br>{{ $order['city'] }}, India</p><span class="small muted">Illustrative customer details</span></section><section class="panel"><h2>Manage fulfilment</h2><form onsubmit="return false" data-preview-form="Status preview complete. No order was changed."><div class="field"><label for="fulfilment">Order status</label><select class="form-select" id="fulfilment">@foreach(['Processing', 'Shipped', 'Delivered', 'Cancelled'] as $status)<option @selected($status === $order['status'])>{{ $status }}</option>@endforeach</select></div><button class="btn btn-dark w-100">Preview update ↗</button></form></section></aside></div>
@endsection
